spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/interviewcoach-v2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      pool-name: HikariCP-InterviewCoach
      connection-test-query: SELECT 1

  # 邮件配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

# MyBatis配置
mybatis:
  type-aliases-package: com.xinyu.InterviewCoach_v2.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

# OpenAI API配置
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}

# 面试配置
interview:
  max-questions: 5
  default-question-count: 3
  session-timeout-minutes: 60

# 邮箱验证配置
email:
  verification:
    expiration-minutes: 5

# 调试配置（可选）
#debug: true
#logging:
#  level:
#    org.springframework: DEBUG
#    com.xinyu.InterviewCoach_v2: DEBUG